// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/srv/GetTypeDescription.srv - do not modify

#include "Srvs/ROS2GetTypeDescription.h"





const rosidl_service_type_support_t* UROS2GetTypeDescriptionSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(type_description_interfaces, srv, GetTypeDescription);
}

void UROS2GetTypeDescriptionSrv::Init()
{
    type_description_interfaces__srv__GetTypeDescription_Request__init(&GetTypeDescription_req);
    type_description_interfaces__srv__GetTypeDescription_Response__init(&GetTypeDescription_res);
}

void UROS2GetTypeDescriptionSrv::Fini()
{
    type_description_interfaces__srv__GetTypeDescription_Request__fini(&GetTypeDescription_req);
    type_description_interfaces__srv__GetTypeDescription_Response__fini(&GetTypeDescription_res);
}

void UROS2GetTypeDescriptionSrv::SetRequest(const FROSGetTypeDescriptionReq& Request)
{
    Request.SetROS2(GetTypeDescription_req);
}

void UROS2GetTypeDescriptionSrv::GetRequest(FROSGetTypeDescriptionReq& Request) const
{
    Request.SetFromROS2(GetTypeDescription_req);
}

void UROS2GetTypeDescriptionSrv::SetResponse(const FROSGetTypeDescriptionRes& Response)
{
    Response.SetROS2(GetTypeDescription_res);
}

void UROS2GetTypeDescriptionSrv::GetResponse(FROSGetTypeDescriptionRes& Response) const
{
    Response.SetFromROS2(GetTypeDescription_res);
}

void* UROS2GetTypeDescriptionSrv::GetRequest()
{
    return &GetTypeDescription_req;
}

void* UROS2GetTypeDescriptionSrv::GetResponse()
{
    return &GetTypeDescription_res;
}

FString UROS2GetTypeDescriptionSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2GetTypeDescriptionSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}