// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from diagnostic_msgs/srv/SelfTest.srv - do not modify

#include "Srvs/ROS2DiagSelfTest.h"





const rosidl_service_type_support_t* UROS2DiagSelfTestSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(diagnostic_msgs, srv, SelfTest);
}

void UROS2DiagSelfTestSrv::Init()
{
    diagnostic_msgs__srv__SelfTest_Request__init(&SelfTest_req);
    diagnostic_msgs__srv__SelfTest_Response__init(&SelfTest_res);
}

void UROS2DiagSelfTestSrv::Fini()
{
    diagnostic_msgs__srv__SelfTest_Request__fini(&SelfTest_req);
    diagnostic_msgs__srv__SelfTest_Response__fini(&SelfTest_res);
}

void UROS2DiagSelfTestSrv::SetRequest(const FROSDiagSelfTestReq& Request)
{
    Request.SetROS2(SelfTest_req);
}

void UROS2DiagSelfTestSrv::GetRequest(FROSDiagSelfTestReq& Request) const
{
    Request.SetFromROS2(SelfTest_req);
}

void UROS2DiagSelfTestSrv::SetResponse(const FROSDiagSelfTestRes& Response)
{
    Response.SetROS2(SelfTest_res);
}

void UROS2DiagSelfTestSrv::GetResponse(FROSDiagSelfTestRes& Response) const
{
    Response.SetFromROS2(SelfTest_res);
}

void* UROS2DiagSelfTestSrv::GetRequest()
{
    return &SelfTest_req;
}

void* UROS2DiagSelfTestSrv::GetResponse()
{
    return &SelfTest_res;
}

FString UROS2DiagSelfTestSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2DiagSelfTestSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}