// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from diagnostic_msgs/srv/AddDiagnostics.srv - do not modify

#include "Srvs/ROS2DiagAddDiag.h"





const rosidl_service_type_support_t* UROS2DiagAddDiagSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(diagnostic_msgs, srv, AddDiagnostics);
}

void UROS2DiagAddDiagSrv::Init()
{
    diagnostic_msgs__srv__AddDiagnostics_Request__init(&AddDiagnostics_req);
    diagnostic_msgs__srv__AddDiagnostics_Response__init(&AddDiagnostics_res);
}

void UROS2DiagAddDiagSrv::Fini()
{
    diagnostic_msgs__srv__AddDiagnostics_Request__fini(&AddDiagnostics_req);
    diagnostic_msgs__srv__AddDiagnostics_Response__fini(&AddDiagnostics_res);
}

void UROS2DiagAddDiagSrv::SetRequest(const FROSDiagAddDiagReq& Request)
{
    Request.SetROS2(AddDiagnostics_req);
}

void UROS2DiagAddDiagSrv::GetRequest(FROSDiagAddDiagReq& Request) const
{
    Request.SetFromROS2(AddDiagnostics_req);
}

void UROS2DiagAddDiagSrv::SetResponse(const FROSDiagAddDiagRes& Response)
{
    Response.SetROS2(AddDiagnostics_res);
}

void UROS2DiagAddDiagSrv::GetResponse(FROSDiagAddDiagRes& Response) const
{
    Response.SetFromROS2(AddDiagnostics_res);
}

void* UROS2DiagAddDiagSrv::GetRequest()
{
    return &AddDiagnostics_req;
}

void* UROS2DiagAddDiagSrv::GetResponse()
{
    return &AddDiagnostics_res;
}

FString UROS2DiagAddDiagSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2DiagAddDiagSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}