// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from diagnostic_msgs/msg/DiagnosticStatus.msg - do not modify

#include "Msgs/ROS2DiagDiagnosticStatus.h"

#include "Kismet/GameplayStatics.h"



void UROS2DiagDiagnosticStatusMsg::Init()
{
	diagnostic_msgs__msg__DiagnosticStatus__init(&diagnostic_status_msg);
}

void UROS2DiagDiagnosticStatusMsg::Fini()
{
	diagnostic_msgs__msg__DiagnosticStatus__fini(&diagnostic_status_msg);
}

const rosidl_message_type_support_t* UROS2DiagDiagnosticStatusMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(diagnostic_msgs, msg, DiagnosticStatus);
}

void UROS2DiagDiagnosticStatusMsg::SetMsg(const FROSDiagDiagnosticStatus& Inputs)
{
    Inputs.SetROS2(diagnostic_status_msg);
}

void UROS2DiagDiagnosticStatusMsg::GetMsg(FROSDiagDiagnosticStatus& Outputs) const
{
    Outputs.SetFromROS2(diagnostic_status_msg);
}

void* UROS2DiagDiagnosticStatusMsg::Get()
{
	return &diagnostic_status_msg;
}

FString UROS2DiagDiagnosticStatusMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}