// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/Field.msg - do not modify

#include "Msgs/ROS2Field.h"

#include "Kismet/GameplayStatics.h"



void UROS2FieldMsg::Init()
{
	type_description_interfaces__msg__Field__init(&field_msg);
}

void UROS2FieldMsg::Fini()
{
	type_description_interfaces__msg__Field__fini(&field_msg);
}

const rosidl_message_type_support_t* UROS2FieldMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, Field);
}

void UROS2FieldMsg::SetMsg(const FROSField& Inputs)
{
    Inputs.SetROS2(field_msg);
}

void UROS2FieldMsg::GetMsg(FROSField& Outputs) const
{
    Outputs.SetFromROS2(field_msg);
}

void* UROS2FieldMsg::Get()
{
	return &field_msg;
}

FString UROS2FieldMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}