// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from diagnostic_msgs/msg/KeyValue.msg - do not modify

#include "Msgs/ROS2DiagKeyValue.h"

#include "Kismet/GameplayStatics.h"



void UROS2DiagKeyValueMsg::Init()
{
	diagnostic_msgs__msg__KeyValue__init(&key_value_msg);
}

void UROS2DiagKeyValueMsg::Fini()
{
	diagnostic_msgs__msg__KeyValue__fini(&key_value_msg);
}

const rosidl_message_type_support_t* UROS2DiagKeyValueMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(diagnostic_msgs, msg, KeyValue);
}

void UROS2DiagKeyValueMsg::SetMsg(const FROSDiagKeyValue& Inputs)
{
    Inputs.SetROS2(key_value_msg);
}

void UROS2DiagKeyValueMsg::GetMsg(FROSDiagKeyValue& Outputs) const
{
    Outputs.SetFromROS2(key_value_msg);
}

void* UROS2DiagKeyValueMsg::Get()
{
	return &key_value_msg;
}

FString UROS2DiagKeyValueMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}