// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/TypeDescription.msg - do not modify

#include "Msgs/ROS2TypeDescription.h"

#include "Kismet/GameplayStatics.h"



void UROS2TypeDescriptionMsg::Init()
{
	type_description_interfaces__msg__TypeDescription__init(&type_description_msg);
}

void UROS2TypeDescriptionMsg::Fini()
{
	type_description_interfaces__msg__TypeDescription__fini(&type_description_msg);
}

const rosidl_message_type_support_t* UROS2TypeDescriptionMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, TypeDescription);
}

void UROS2TypeDescriptionMsg::SetMsg(const FROSTypeDescription& Inputs)
{
    Inputs.SetROS2(type_description_msg);
}

void UROS2TypeDescriptionMsg::GetMsg(FROSTypeDescription& Outputs) const
{
    Outputs.SetFromROS2(type_description_msg);
}

void* UROS2TypeDescriptionMsg::Get()
{
	return &type_description_msg;
}

FString UROS2TypeDescriptionMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}