// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/TypeSource.msg - do not modify

#include "Msgs/ROS2TypeSource.h"

#include "Kismet/GameplayStatics.h"



void UROS2TypeSourceMsg::Init()
{
	type_description_interfaces__msg__TypeSource__init(&type_source_msg);
}

void UROS2TypeSourceMsg::Fini()
{
	type_description_interfaces__msg__TypeSource__fini(&type_source_msg);
}

const rosidl_message_type_support_t* UROS2TypeSourceMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, TypeSource);
}

void UROS2TypeSourceMsg::SetMsg(const FROSTypeSource& Inputs)
{
    Inputs.SetROS2(type_source_msg);
}

void UROS2TypeSourceMsg::GetMsg(FROSTypeSource& Outputs) const
{
    Outputs.SetFromROS2(type_source_msg);
}

void* UROS2TypeSourceMsg::Get()
{
	return &type_source_msg;
}

FString UROS2TypeSourceMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}