// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from diagnostic_msgs/msg/DiagnosticArray.msg - do not modify

#include "Msgs/ROS2DiagDiagnosticArray.h"

#include "Kismet/GameplayStatics.h"



void UROS2DiagDiagnosticArrayMsg::Init()
{
	diagnostic_msgs__msg__DiagnosticArray__init(&diagnostic_array_msg);
}

void UROS2DiagDiagnosticArrayMsg::Fini()
{
	diagnostic_msgs__msg__DiagnosticArray__fini(&diagnostic_array_msg);
}

const rosidl_message_type_support_t* UROS2DiagDiagnosticArrayMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(diagnostic_msgs, msg, DiagnosticArray);
}

void UROS2DiagDiagnosticArrayMsg::SetMsg(const FROSDiagDiagnosticArray& Inputs)
{
    Inputs.SetROS2(diagnostic_array_msg);
}

void UROS2DiagDiagnosticArrayMsg::GetMsg(FROSDiagDiagnosticArray& Outputs) const
{
    Outputs.SetFromROS2(diagnostic_array_msg);
}

void* UROS2DiagDiagnosticArrayMsg::Get()
{
	return &diagnostic_array_msg;
}

FString UROS2DiagDiagnosticArrayMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}